### ISSUE TITLE
What's the best way of load-balancing nb2kg to more than 1 server?

### ISSUE THREAD

**Issue by rs2** [jupyter/kernel_gateway_demos#46]
A very simple use case. Scale notebook server horizontally, i.e. on multiple hosts. Use a simple round-robin load-balancing method. Ideally plug this load balancer into `kernel-gateway` itself, or if easier, into `nb2kg`. 

What would be the best approach?

**Comment by parente** [comment]
I'm not sure how round-robin load-balancing can work with kernels which inherently hold state in RAM, unless that state is replicated across all kernels.

**Comment by kevin-bates** [comment]
@rs2 - You might be interested in looking at the recently opened incubator project - [Jupyter Enterprise Gateway](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/).  The DistributedProcessProxy implements this exact behavior.

Closing this issue since this isn't something that NB2KG is designed to do.

**Comment by rs2** [comment]
@kevin-bates :+1:
